articles_index:
    path:  /articles
    defaults: { _controller: ArticlesBundle:Index:index }
    
articles_view:
    path:  /article/{id}/view
    defaults: { _controller: ArticlesBundle:Index:view }
    
articles_admin_index:
    path:  /admin/articles
    defaults: { _controller: ArticlesBundle:IndexAdmin:index }
    
articles_admin_add:
    path:  /admin/articles/add
    defaults: { _controller: ArticlesBundle:IndexAdmin:add }
    
articles_admin_edit:
    path:  /admin/articles/edit
    defaults: { _controller: ArticlesBundle:IndexAdmin:edit }
    
articles_admin_delete:
    path:  /admin/articles/edit
    defaults: { _controller: ArticlesBundle:IndexAdmin:delete }