<?php

namespace ArticlesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
}
