<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends EntityRepository
{
    /**
     * Get FieldNames
     * 
     * @return array
     */
    public function getFieldNames()
    {
        return $this->getClassMetadata()->getFieldNames();
    }
    
    /**
     * Gets the specified field's value off the given entity.
     *
     * @param object $entity
     * @param string $field
     *
     * @return mixed
     */
    public function getFieldValue($entity, $field)
    {
        return $this->getClassMetadata()->getFieldValue($entity, $field);
    }
}