<?php

namespace AppBundle\Repository;

use AppBundle\Repository\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Setting extends Repository
{
    public function getSystemLogo()
    {
        return $this->findOneBy(array(
            'name' => 'system_logo'
        ));
    } 
}
