<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Setting extends EntityRepository
{
    public function getSystemLogo()
    {
        return $this->findOneBy(array(
            'name' => 'system_logo'
        ));
    } 
}
