<?php

namespace GalleriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function getMainGallery()
    {
        return $this->findOneBy(array(
            'id' => 1
        ));
    } 
}
