#security:
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
#
#    providers:
#        administrators:
#            entity:
#                class: AppBundle:User
#
#    firewalls:
#        secured_area:
#            pattern:   ^/admin
#            form_login:
#                login_path: login
#                check_path: login_check
#
#    encoders:
#        Kit\SystemBundle\Entity\User:
#            algorithm: bcrypt
#            cost: 12
#
#    access_control:
#        - { path: ^/admin, roles: ROLE_USER }
security:
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        # ...
        default:
            anonymous: ~
            http_basic: ~

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }