security:

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        main:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    access_control:
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

#security:
#    providers:
#        in_memory:
#            memory:
#                users:
#                    ryan:
#                        password: ryanpass
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: kitten
#                        roles: 'ROLE_ADMIN'
#
#    firewalls:
#        main:
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login
#        
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        
#    access_control:
#        # require ROLE_ADMIN for /admin*
#        - { path: ^/admin, roles: ROLE_ADMIN }