security:
    providers:
        in_database:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
#            provider: in_database
            logout:
                path:   /logout
                target: /
        
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
#            cost: 12
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        
    acl:
        connection: default