security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }