<?php

namespace AdsBundle\Repository;

use AppBundle\Repository\Repository;

/**
 * Ad
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ad extends Repository
{

}