app_index:
    path:  /index
    defaults: { _controller: AppBundle:Default:index }

app_login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }
    
app_register:
    path: /register
    defaults: { _controller: AppBundle:Security:register }
#
#login_check:
#    path: /admin/login_check
#    defaults: { _controller: AppBundle:Security:check }
#    requirements:
#        _username:  \w
#        _password:  \w
#
#logout:
#    path:   /admin/logout

_security_login:
    path:  /login
    defaults: { _controller: AppBundle:Security:login }

_security_check:
    path:  /login_check

_security_logout:
    path:  /logout

admin_home:
    path:  /admin/
    defaults: { _controller: AppBundle:IndexAdmin:index }


_system_admin_index:
    path:  /admin
    defaults: { _controller: AppBundle:IndexAdmin:index }

app_admin_settings:
    path:  /admin/settings
    defaults: { _controller: AppBundle:SettingsAdmin:index }

pages:
    resource: "@AppBundle/Resources/config/routing/pages.yml"