AppBundle\Entity\Page:
    type: entity
    table: system_page
    repositoryClass: AppBundle\Entity\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        slug:
            type:
            length: 255
        title:
            type: string
            length: 255
            NotBlank: ~
        image:
            type: string
            length: 255
        nameInMenu:
            type: string
            length: 255
        body:
            type: text
        keywords:
            type: string
            length: 255
        description:
            type: string
            length: 255
        createdAt:
            type: datetime
            gedmo:
              timestampable:
                on: create
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        deletedAt:
            type: datetime
            column: deleted_at
    lifecycleCallbacks: {  }
