<?php

namespace ArticlesBundle\Repository;

use AppBundle\Repository\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends Repository
{
    const limit = 2;

    public function getPagination($page)
    {
        $qb = $this->createQueryBuilder('p')
                  // ->orderBy('p.created', 'DESC')
                   ->getQuery();
        
        return $this->paginate($qb, $page, self::limit);
    }
}